'use client'

import { ThoughtList } from '@/components/v2/thoughts/ThoughtList'
import { Brain } from 'lucide-react'

export default function ThoughtsPage() {
  return (
    <div className="container mx-auto py-8 px-4 max-w-7xl">
      <div className="mb-8 space-y-2">
        <div className="flex items-center gap-3">
          <Brain className="w-8 h-8 text-primary" />
          <h1 className="text-4xl font-bold tracking-tight">Thought Management</h1>
        </div>
        <p className="text-muted-foreground">
          Generate, view, and manage AI reasoning thoughts generated by the Thought Agent.
        </p>
      </div>

      <ThoughtList />
    </div>
  )
}

